"""added adjustment to Course

Revision ID: 10c71e0683c1
Revises: fc578847d030
Create Date: 2023-05-30 10:24:10.948760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c71e0683c1'
down_revision = 'fc578847d030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('session_table')
    op.add_column('courses', sa.Column('adjustment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'adjustment')
    op.create_table('session_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='session_table_pkey'),
    sa.UniqueConstraint('session_id', name='session_table_session_id_key')
    )
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bib', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('runner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name='participants_race_id_fkey'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name='participants_runner_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='participants_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='participants_pkey')
    )
    # ### end Alembic commands ###
