"""empty message

Revision ID: 120083e7076b
Revises: 244ae855dd64
Create Date: 2020-03-26 10:27:55.455126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120083e7076b'
down_revision = '244ae855dd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_schools',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_schools')
    # ### end Alembic commands ###
