"""Added non_duplicate_pairs table

Revision ID: 4bde90b74cb9
Revises: 5cd265941068
Create Date: 2023-11-07 09:04:15.581888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bde90b74cb9'
down_revision = '5cd265941068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non_duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner1_id', sa.Integer(), nullable=False),
    sa.Column('runner2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['runner1_id'], ['runners.id'], ),
    sa.ForeignKeyConstraint(['runner2_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('non_duplicates')
    # ### end Alembic commands ###
