"""added race_teams table to associate teams with a race

Revision ID: 5274e5575289
Revises: 7ef8b94f48d5
Create Date: 2020-04-14 14:44:14.789703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5274e5575289'
down_revision = '7ef8b94f48d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_teams',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_teams')
    # ### end Alembic commands ###
