"""added winner and loser score to RaceResult

Revision ID: 7cbb7dde1960
Revises: a0b4d444e70e
Create Date: 2023-04-27 10:52:05.158853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cbb7dde1960'
down_revision = 'a0b4d444e70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_table')
    op.add_column('race_result', sa.Column('loser_score', sa.Integer(), nullable=True))
    op.add_column('race_result', sa.Column('winner_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_result', 'winner_score')
    op.drop_column('race_result', 'loser_score')
    op.create_table('session_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='session_table_pkey'),
    sa.UniqueConstraint('session_id', name='session_table_session_id_key')
    )
    # ### end Alembic commands ###
