"""empty message

Revision ID: 8d41d3580335
Revises: 78638eec8bfc
Create Date: 2020-07-22 14:29:34.165759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d41d3580335'
down_revision = '78638eec8bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('city', sa.String(length=32), nullable=True))
    op.add_column('schools', sa.Column('state_abbr', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'state_abbr')
    op.drop_column('schools', 'city')
    # ### end Alembic commands ###
