"""empty message

Revision ID: ed2054ae4322
Revises: c0690512b6eb
Create Date: 2020-09-11 12:55:47.492657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2054ae4322'
down_revision = 'c0690512b6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('league_losses', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('league_wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'league_wins')
    op.drop_column('teams', 'league_losses')
    # ### end Alembic commands ###
